import json
import numpy as np
import pandas as pd
import joblib

MODEL_PATH = "models/fault_classifier.joblib"
FEATURES_PATH = "models/feature_columns.joblib"
LABELS_PATH = "models/label_columns.joblib"

THRESHOLD = 0.5

clf = joblib.load(MODEL_PATH)
feature_columns = joblib.load(FEATURES_PATH)
label_columns = joblib.load(LABELS_PATH)


def extract_features(row):                          # kept identical to train.py so
    comps_dict = json.loads(row["component_values"]) # inference features always match
    design_dict = json.loads(row["design_values"]) if "design_values" in row and pd.notna(row.get("design_values")) else {}

    volts = list(json.loads(row["node_voltages"]).values())
    currs = list(json.loads(row["branch_currents"]).values())

    volt_abs = np.abs(volts)
    curr_abs = np.abs(currs)

    deviations = []
    for name, val in comps_dict.items():
        nom = design_dict.get(name)
        if nom:
            deviations.append(abs(val - nom) / nom)

    deviations_sorted = sorted(deviations, reverse=True)
    max_dev = deviations_sorted[0] if deviations_sorted else 0
    second_dev = deviations_sorted[1] if len(deviations_sorted) > 1 else 0
    dev_ratio = (second_dev / max_dev) if max_dev > 0 else 0
    n_dev_over_20pct = sum(d > 0.20 for d in deviations)

    n_passive = sum(
        1 for name in comps_dict
        if not (name.upper().startswith('V') or name.upper().startswith('I'))
    )

    return pd.Series({
        "n_components": len(comps_dict),
        "n_nodes": len(volts),
        "volt_mean": np.mean(volts) if volts else 0,
        "volt_max": np.max(volts) if volts else 0,
        "volt_min": np.min(volts) if volts else 0,
        "n_currents": len(currs),
        "curr_mean_abs": np.mean(curr_abs) if currs else 0,
        "curr_max_abs": np.max(curr_abs) if currs else 0,
        "volt_std": np.std(volts) if volts else 0,
        "volt_range": (np.max(volts) - np.min(volts)) if volts else 0,
        "curr_std_abs": np.std(curr_abs) if currs else 0,
        "curr_range_abs": (np.max(curr_abs) - np.min(curr_abs)) if currs else 0,
        "missing_current_ratio":
            (n_passive - len(currs)) / max(n_passive, 1),
        "n_missing_currents": n_passive - len(currs),
        "max_deviation_ratio": max_dev,
        "second_deviation_ratio": second_dev,
        "deviation_ratio_2nd_over_1st": dev_ratio,
        "n_components_deviated_over_20pct": n_dev_over_20pct,
    })


def predict_one(sample, threshold=THRESHOLD):
    row = pd.Series(sample)
    features = extract_features(row)
    X_new = pd.DataFrame([features]).reindex(columns=feature_columns, fill_value=0)

    proba_per_label = clf.predict_proba(X_new)

    label_probs = {}
    for i, label in enumerate(label_columns):
        classes = clf.classes_[i]
        arr = proba_per_label[i][0]
        if 1 in list(classes):
            yes_idx = list(classes).index(1)
            p_yes = arr[yes_idx]
        else:
            p_yes = 0.0
        label_probs[label] = float(p_yes)

    fired = [label for label, p in label_probs.items() if p >= threshold]

    if len(fired) == 0:
        overall_pred = "normal"
    elif len(fired) == 1:
        overall_pred = fired[0]
    else:
        overall_pred = "multi_fault"

    return overall_pred, label_probs


# --------------------------------------------------------------------------
# 50 real, ngspice-verified test cases (10 circuits x 5 fault types).
# Generated by running the actual generator/simulator (not hand-typed), so
# node_voltages / branch_currents are genuine ngspice .op solutions for the
# faulted component_values shown, keyed against each circuit's design_values.
# --------------------------------------------------------------------------
TEST_CASES = [
    # source: series_parallel_R1R2R3R4
    {"expected": "normal",
     "component_values": '{"R1": 992.953311, "R2": 1972.067934, "R3": 3018.112137, "R4": 1474.346177}',
     "design_values": '{"R1": 1000, "R2": 2000, "R3": 3000, "R4": 1500}',
     "node_voltages": '{"a": 7.287032, "b": 4.028239, "in": 10.0}',
     "branch_currents": '{"R1": 0.002732221, "R2": 0.001652475, "R3": 0.001079746, "R4": 0.002732221}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 90.794413, "R2": 2026.14817, "R3": 2954.856235, "R4": 1483.394338}',
     "design_values": '{"R1": 1000, "R2": 2000, "R3": 3000, "R4": 1500}',
     "node_voltages": '{"a": 9.672949, "b": 5.34335, "in": 10.0}',
     "branch_currents": '{"R1": 0.00360211, "R2": 0.002136862, "R3": 0.001465248, "R4": 0.00360211}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 32855.431693, "R2": 1989.791803, "R3": 3005.729336, "R4": 1473.767338}',
     "design_values": '{"R1": 1000, "R2": 2000, "R3": 3000, "R4": 1500}',
     "node_voltages": '{"a": 0.7518333, "b": 0.4148369, "in": 10.0}',
     "branch_currents": '{"R1": 0.0002814806, "R2": 0.0001693626, "R3": 0.000112118, "R4": 0.0002814806}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 5.61e-06, "R2": 2018.355623, "R3": 2974.552532, "R4": 1528.810491}',
     "design_values": '{"R1": 1000, "R2": 2000, "R3": 3000, "R4": 1500}',
     "node_voltages": '{"a": 0.0, "b": 0.0, "in": 10.0}',
     "branch_currents": '{"R2": 0.0, "R3": 0.0, "R4": 0.0}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 17806.798944, "R2": 2027.197422, "R3": 3053.361731, "R4": 96.016203}',
     "design_values": '{"R1": 1000, "R2": 2000, "R3": 3000, "R4": 1500}',
     "node_voltages": '{"a": 0.6873755, "b": 0.05021469, "in": 10.0}',
     "branch_currents": '{"R1": 0.0005229814, "R2": 0.0003143062, "R3": 0.0002086752, "R4": 0.0005229814}'},

    # source: multisource_5R_network
    {"expected": "normal",
     "component_values": '{"R1": 1982.273685, "R2": 1993.223721, "R3": 994.350847, "R4": 1523.05157, "R5": 4073.236993, "I1": 5}',
     "design_values": '{"R1": 2000, "R2": 2000, "R3": 1000, "R4": 1500, "R5": 4000}',
     "node_voltages": '{"A": 10.0, "B": 15.0, "C": 2631.305}',
     "branch_currents": '{"R1": 0.005044712, "R2": -0.0025085, "R3": -2.6362, "R4": -1.7178, "R5": 0.6459985}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 147.860242, "R2": 2036.247834, "R3": 1007.619746, "R4": 1500.929486, "R5": 4018.81484, "I1": 5}',
     "design_values": '{"R1": 2000, "R2": 2000, "R3": 1000, "R4": 1500, "R5": 4000}',
     "node_voltages": '{"A": 10.0, "B": 15.0, "C": 2631.645}',
     "branch_currents": '{"R1": 0.06763143, "R2": -0.0024555, "R3": -2.60182, "R4": -1.74335, "R5": 0.654831}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 88689.913964, "R2": 2005.342689, "R3": 1001.464748, "R4": 1526.936926, "R5": 4018.197962, "I1": 5}',
     "design_values": '{"R1": 2000, "R2": 2000, "R3": 1000, "R4": 1500, "R5": 4000}',
     "node_voltages": '{"A": 10.0, "B": 15.0, "C": 2638.795}',
     "branch_currents": '{"R1": 0.0001127524, "R2": -0.00249334, "R3": -2.62495, "R4": -1.71834, "R5": 0.6567111}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 1998.289755, "R2": 2015.364542, "R3": 2.32e-06, "R4": 1482.3129, "R5": 4072.323352, "I1": 5}',
     "design_values": '{"R1": 2000, "R2": 2000, "R3": 1000, "R4": 1500, "R5": 4000}',
     "node_voltages": '{"A": 10.0, "B": 15.0, "C": 5444.708}',
     "branch_currents": '{"R1": 0.005004279, "R2": -0.00248094, "R4": -3.663, "R5": 1.337003}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 2023.071941, "R2": 75790.359323, "R3": 987.805841, "R4": 1484.36326, "R5": 594.178009, "I1": 5}',
     "design_values": '{"R1": 2000, "R2": 2000, "R3": 1000, "R4": 1500, "R5": 4000}',
     "node_voltages": '{"A": 10.0, "B": 15.0, "C": 1490.11}',
     "branch_currents": '{"R1": 0.004942978, "R2": -6.59715e-05, "R3": -1.49838, "R4": -0.993766, "R5": 2.507852}'},

    # source: current_source_single_R
    {"expected": "normal",
     "component_values": '{"Rx": 416.303876, "I1": 0.012}',
     "design_values": '{"Rx": 416.67}',
     "node_voltages": '{"p": 4.995647}',
     "branch_currents": '{"Rx": 0.012}'},
    {"expected": "partial_short",
     "component_values": '{"Rx": 31.184614, "I1": 0.012}',
     "design_values": '{"Rx": 416.67}',
     "node_voltages": '{"p": 0.3742154}',
     "branch_currents": '{"Rx": 0.012}'},
    {"expected": "partial_open",
     "component_values": '{"Rx": 17205.383138, "I1": 0.012}',
     "design_values": '{"Rx": 416.67}',
     "node_voltages": '{"p": 206.4646}',
     "branch_currents": '{"Rx": 0.012}'},
    {"expected": "wrong_component_type",
     "component_values": '{"Rx": 5.74e-06, "I1": 0.012}',
     "design_values": '{"Rx": 416.67}',
     "node_voltages": '{"p": 0.02090592}',
     "branch_currents": '{}'},
    {"expected": "multi_fault",
     "component_values": '{"Rx": 460.327333, "I1": 0.012}',
     "design_values": '{"Rx": 416.67}',
     "node_voltages": '{"p": 5.523928}',
     "branch_currents": '{"Rx": 0.012}'},

    # source: voltage_divider_12k_9k
    {"expected": "normal",
     "component_values": '{"R1": 11971.259958, "R2": 8885.918839}',
     "design_values": '{"R1": 12000, "R2": 9000}',
     "node_voltages": '{"o": 2.982255, "s": 7.0}',
     "branch_currents": '{"R1": 0.0003356159, "R2": 0.0003356159}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 12108.09277, "R2": 949.73752}',
     "design_values": '{"R1": 12000, "R2": 9000}',
     "node_voltages": '{"o": 0.5091323, "s": 7.0}',
     "branch_currents": '{"R1": 0.0005360768, "R2": 0.0005360768}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 299354.132532, "R2": 9022.222579}',
     "design_values": '{"R1": 12000, "R2": 9000}',
     "node_voltages": '{"o": 0.2048003, "s": 7.0}',
     "branch_currents": '{"R1": 2.269954e-05, "R2": 2.269954e-05}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 11878.874784, "R2": 9.31e-06}',
     "design_values": '{"R1": 12000, "R2": 9000}',
     "node_voltages": '{"o": 7.0, "s": 7.0}',
     "branch_currents": '{"R1": 0.0}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 536729.730175, "R2": 270.153537}',
     "design_values": '{"R1": 12000, "R2": 9000}',
     "node_voltages": '{"o": 0.003521555, "s": 7.0}',
     "branch_currents": '{"R1": 1.303538e-05, "R2": 1.303538e-05}'},

    # source: kvl_series_loop_ABCDEF
    {"expected": "normal",
     "component_values": '{"R_FA": 7957.104805, "R_AB": 5961.115125, "R_BC": 11980.161969, "R_DE": 4032.50422}',
     "design_values": '{"R_FA": 8000, "R_AB": 6000, "R_BC": 12000, "R_DE": 4000}',
     "node_voltages": '{"A": 7.975479, "B": 13.95036, "C": 25.95818, "D": 1.958184, "E": 6.0}',
     "branch_currents": '{"R_FA": -0.00100231, "R_AB": -0.00100231, "R_BC": -0.00100231, "R_DE": -0.00100231}'},
    {"expected": "partial_short",
     "component_values": '{"R_FA": 7866.899605, "R_AB": 748.612905, "R_BC": 12194.831371, "R_DE": 3949.048223}',
     "design_values": '{"R_FA": 8000, "R_AB": 6000, "R_BC": 12000, "R_DE": 4000}',
     "node_voltages": '{"A": 9.532019, "B": 10.43908, "C": 25.21509, "D": 1.215091, "E": 6.0}',
     "branch_currents": '{"R_FA": -0.00121166, "R_AB": -0.00121166, "R_BC": -0.00121166, "R_DE": -0.00121166}'},
    {"expected": "partial_open",
     "component_values": '{"R_FA": 7845.386151, "R_AB": 47988.084416, "R_BC": 11885.064905, "R_DE": 4017.308388}',
     "design_values": '{"R_FA": 8000, "R_AB": 6000, "R_BC": 12000, "R_DE": 4000}',
     "node_voltages": '{"A": 3.280948, "B": 23.34961, "C": 28.31996, "D": 4.319958, "E": 6.0}',
     "branch_currents": '{"R_FA": -0.000418201, "R_AB": -0.000418201, "R_BC": -0.000418201, "R_DE": -0.000418201}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R_FA": 7904.56584, "R_AB": 5954.878177, "R_BC": 5.01e-06, "R_DE": 4041.519721}',
     "design_values": '{"R_FA": 8000, "R_AB": 6000, "R_BC": 12000, "R_DE": 4000}',
     "node_voltages": '{"A": 0.0, "B": 0.0, "C": 30.0, "D": 6.0, "E": 6.0}',
     "branch_currents": '{"R_FA": 0.0, "R_AB": 0.0, "R_DE": 0.0}'},
    {"expected": "multi_fault",
     "component_values": '{"R_FA": 8102.054445, "R_AB": 5983.722621, "R_BC": 695.743771, "R_DE": 196839.297275}',
     "design_values": '{"R_FA": 8000, "R_AB": 6000, "R_BC": 12000, "R_DE": 4000}',
     "node_voltages": '{"A": 1.148571, "B": 1.996842, "C": 2.095473, "D": -21.9045, "E": 6.0}',
     "branch_currents": '{"R_FA": -0.000141763, "R_AB": -0.000141763, "R_BC": -0.000141763, "R_DE": -0.000141763}'},

    # source: vdr_parallel_network
    {"expected": "normal",
     "component_values": '{"R1": 5944.568809, "R2": 11761.738902, "R3": 11934.787849, "I1": 0.012}',
     "design_values": '{"R1": 6000, "R2": 12000, "R3": 12000}',
     "node_voltages": '{"T": 35.60504}',
     "branch_currents": '{"R1": 0.005989508, "R2": 0.003027192, "R3": 0.002983299}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 5923.909893, "R2": 964.643531, "R3": 11800.267469, "I1": 0.012}',
     "design_values": '{"R1": 6000, "R2": 12000, "R3": 12000}',
     "node_voltages": '{"T": 9.300857}',
     "branch_currents": '{"R1": 0.001570054, "R2": 0.009641756, "R3": 0.0007881904}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 207536.791794, "R2": 12041.079976, "R3": 12014.010983, "I1": 0.012}',
     "design_values": '{"R1": 6000, "R2": 12000, "R3": 12000}',
     "node_voltages": '{"T": 70.13295}',
     "branch_currents": '{"R1": 0.0003379302, "R2": 0.005824473, "R3": 0.005837597}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 6080.46949, "R2": 12188.132331, "R3": 7.31e-06, "I1": 0.012}',
     "design_values": '{"R1": 6000, "R2": 12000, "R3": 12000}',
     "node_voltages": '{"T": 48.67996}',
     "branch_currents": '{"R1": 0.008005954, "R2": 0.003994046}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 762.089808, "R2": 361604.713108, "R3": 11774.957053, "I1": 0.012}',
     "design_values": '{"R1": 6000, "R2": 12000, "R3": 12000}',
     "node_voltages": '{"T": 8.572208}',
     "branch_currents": '{"R1": 0.01124829, "R2": 2.370602e-05, "R3": 0.0007280033}'},

    # source: wheatstone_bridge
    {"expected": "normal",
     "component_values": '{"R1": 101.025766, "R3": 197.845889, "R2": 150.899594, "R4": 299.524081, "Rg": 50.691063}',
     "design_values": '{"R1": 100, "R3": 200, "R2": 150, "R4": 300, "Rg": 50}',
     "node_voltages": '{"mid1": 13.25798, "mid2": 13.27197, "pos": 20.0}',
     "branch_currents": '{"R1": 0.06673567, "R3": 0.06701164, "R2": 0.04458616, "R4": 0.04431018, "Rg": -0.000275972}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 10.690592, "R3": 197.067528, "R2": 149.894524, "R4": 299.829577, "Rg": 50.945018}',
     "design_values": '{"R1": 100, "R3": 200, "R2": 150, "R4": 300, "Rg": 50}',
     "node_voltages": '{"mid1": 18.61587, "mid2": 16.8324, "pos": 20.0}',
     "branch_currents": '{"R1": 0.1294721, "R3": 0.0944644, "R2": 0.0211322, "R4": 0.05613989, "Rg": 0.03500769}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 101.872433, "R3": 1671.515809, "R2": 148.611943, "R4": 296.518047, "Rg": 50.891175}',
     "design_values": '{"R1": 100, "R3": 200, "R2": 150, "R4": 300, "Rg": 50}',
     "node_voltages": '{"mid1": 16.69243, "mid2": 15.54833, "pos": 20.0}',
     "branch_currents": '{"R1": 0.03246776, "R3": 0.009986403, "R2": 0.02995501, "R4": 0.05243636, "Rg": 0.02248135}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 99.966784, "R3": 199.606082, "R2": 2.09e-06, "R4": 295.688487, "Rg": 49.68792}',
     "design_values": '{"R1": 100, "R3": 200, "R2": 150, "R4": 300, "Rg": 50}',
     "node_voltages": '{"mid1": 11.17154, "mid2": 9.564336, "pos": 20.0}',
     "branch_currents": '{"R1": 0.08831393, "R3": 0.05596794, "R4": 0.03234599, "Rg": 0.03234599}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 101.701662, "R3": 3840.412354, "R2": 10.661056, "R4": 297.367652, "Rg": 49.103235}',
     "design_values": '{"R1": 100, "R3": 200, "R2": 150, "R4": 300, "Rg": 50}',
     "node_voltages": '{"mid1": 19.37384, "mid2": 19.31923, "pos": 20.0}',
     "branch_currents": '{"R1": 0.00615682, "R3": 0.005044729, "R2": 0.06385541, "R4": 0.0649675, "Rg": 0.001112091}'},

    # source: resistor_cube
    {"expected": "normal",
     "component_values": '{"R1": 0.998436, "R2": 0.986502, "R3": 0.980593, "R4": 1.002062, "R5": 1.005627, "R6": 1.016392, "R7": 0.983561, "R8": 1.004888, "R9": 0.994834, "R10": 1.000179, "R11": 0.985835, "R12": 0.991332}',
     "design_values": '{"R1": 1, "R2": 1, "R3": 1, "R4": 1, "R5": 1, "R6": 1, "R7": 1, "R8": 1, "R9": 1, "R10": 1, "R11": 1, "R12": 1}',
     "node_voltages": '{"n1": 4.793263, "n2": 4.770551, "n3": 7.194827, "n4": 4.769898, "n5": 7.210942, "n6": 7.18091, "n7": 12.0}',
     "branch_currents": '{"R1": -4.80077, "R2": -4.83582, "R3": -4.8643, "R4": -2.39662, "R5": -2.40415, "R6": -2.38518, "R7": -2.45065, "R8": -4.7818, "R9": -2.45372, "R10": -2.41058, "R11": -4.85787, "R12": -4.86123}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 0.988725, "R2": 0.99599, "R3": 1.000716, "R4": 0.995343, "R5": 0.984922, "R6": 0.026482, "R7": 1.008995, "R8": 1.015892, "R9": 0.981644, "R10": 1.002494, "R11": 1.010298, "R12": 0.981525}',
     "design_values": '{"R1": 1, "R2": 1, "R3": 1, "R4": 1, "R5": 1, "R6": 1, "R7": 1, "R8": 1, "R9": 1, "R10": 1, "R11": 1, "R12": 1}',
     "node_voltages": '{"n1": 4.353648, "n2": 5.907282, "n3": 6.01889, "n4": 4.906227, "n5": 7.042742, "n6": 7.639276, "n7": 12.0}',
     "branch_currents": '{"R1": -4.4033, "R2": -5.93107, "R3": -4.90272, "R4": -1.67303, "R5": -2.73026, "R6": -4.21451, "R7": -1.71655, "R8": -5.88754, "R9": -2.17647, "R10": -2.72625, "R11": -4.90673, "R12": -4.4428}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 0.98329, "R2": 13.716829, "R3": 1.011105, "R4": 1.000459, "R5": 0.982171, "R6": 1.000157, "R7": 0.995115, "R8": 1.018035, "R9": 0.985447, "R10": 1.014283, "R11": 1.019845, "R12": 1.009283}',
     "design_values": '{"R1": 1, "R2": 1, "R3": 1, "R4": 1, "R5": 1, "R6": 1, "R7": 1, "R8": 1, "R9": 1, "R10": 1, "R11": 1, "R12": 1}',
     "node_voltages": '{"n1": 5.312994, "n2": 8.207861, "n3": 8.486705, "n4": 5.358688, "n5": 7.504246, "n6": 8.525878, "n7": 12.0}',
     "branch_currents": '{"R1": -5.40328, "R2": -0.598379, "R3": -5.29983, "R4": -3.17225, "R5": -2.23103, "R6": -0.278801, "R7": -0.319578, "R8": -3.45106, "R9": -2.17724, "R10": -3.12259, "R11": -4.40827, "R12": -3.44217}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 0.98675, "R2": 1.011395, "R3": 0.984603, "R4": 1.001229, "R5": 1.005453, "R6": 0.994391, "R7": 1.014918, "R8": 1.002207, "R9": 1.003202, "R10": 1.015301, "R11": 8.71e-06, "R12": 1.019718}',
     "design_values": '{"R1": 1, "R2": 1, "R3": 1, "R4": 1, "R5": 1, "R6": 1, "R7": 1, "R8": 1, "R9": 1, "R10": 1, "R11": 1, "R12": 1}',
     "node_voltages": '{"n1": 3.23253, "n2": 4.355521, "n3": 6.522601, "n4": 3.212249, "n5": 3.222378, "n6": 6.514398, "n7": 12.0}',
     "branch_currents": '{"R1": -3.27594, "R2": -4.30645, "R3": -3.26248, "R4": -3.28603, "R5": 0.01009683, "R6": -2.1793, "R7": -2.12714, "R8": -5.46534, "R9": -0.0100968, "R10": -3.25238, "R12": -5.37953}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 0.023413, "R2": 0.982176, "R3": 1.002685, "R4": 33.719454, "R5": 1.000924, "R6": 1.001365, "R7": 0.99653, "R8": 0.992046, "R9": 0.985349, "R10": 0.994649, "R11": 1.013139, "R12": 0.986345}',
     "design_values": '{"R1": 1, "R2": 1, "R3": 1, "R4": 1, "R5": 1, "R6": 1, "R7": 1, "R8": 1, "R9": 1, "R10": 1, "R11": 1, "R12": 1}',
     "node_voltages": '{"n1": 0.1293121, "n2": 5.176232, "n3": 8.480641, "n4": 4.198115, "n5": 5.409607, "n6": 7.139657, "n7": 12.0}',
     "branch_currents": '{"R1": -5.52309, "R2": -5.27017, "R3": -4.18687, "R4": -0.247671, "R5": -5.27542, "R6": -3.29991, "R7": -1.97026, "R8": -3.54758, "R9": -1.22951, "R10": -2.95737, "R11": -6.50493, "R12": -4.92763}'},

    # source: current_source_voltage_divider
    {"expected": "normal",
     "component_values": '{"R1": 1015.574097, "R2": 2022.637934, "I1": 0.01}',
     "design_values": '{"R1": 1000, "R2": 2000}',
     "node_voltages": '{"out": 6.761012}',
     "branch_currents": '{"R1": 0.00665733, "R2": 0.00334267}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 998.610622, "R2": 69.109684, "I1": 0.01}',
     "design_values": '{"R1": 1000, "R2": 2000}',
     "node_voltages": '{"out": 0.6463646}',
     "branch_currents": '{"R1": 0.0006472639, "R2": 0.009352736}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 990.639508, "R2": 71716.033376, "I1": 0.01}',
     "design_values": '{"R1": 1000, "R2": 2000}',
     "node_voltages": '{"out": 9.771419}',
     "branch_currents": '{"R1": 0.009863748, "R2": 0.0001362515}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 9.5e-06, "R2": 2027.337832, "I1": 0.01}',
     "design_values": '{"R1": 1000, "R2": 2000}',
     "node_voltages": '{"out": 20.27338}',
     "branch_currents": '{"R2": 0.01}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 120.488335, "R2": 45240.674958, "I1": 0.01}',
     "design_values": '{"R1": 1000, "R2": 2000}',
     "node_voltages": '{"out": 1.201683}',
     "branch_currents": '{"R1": 0.009973438, "R2": 2.6562e-05}'},

    # source: nilsson_ex3_4_current_voltage_division
    {"expected": "normal",
     "component_values": '{"R1": 35.645833, "R2": 44.817195, "R3": 10.086884, "R4": 39.218242, "R5": 9.805892, "R6": 30.180837, "R7": 24.30465, "I1": 8}',
     "design_values": '{"R1": 36, "R2": 44, "R3": 10, "R4": 40, "R5": 10, "R6": 30, "R7": 24}',
     "node_voltages": '{"T": 48.38615, "n1": 26.95066, "n2": 24.42781, "n3": 18.43741}',
     "branch_currents": '{"R1": 0.6013464, "R2": 0.6013464, "R3": 4.796937, "R4": 0.6108979, "R5": 0.6108979, "R6": 0.6108979, "R7": 1.990819}'},
    {"expected": "partial_short",
     "component_values": '{"R1": 36.20864, "R2": 44.228284, "R3": 9.967186, "R4": 39.81718, "R5": 0.56744, "R6": 30.533906, "R7": 24.273239, "I1": 8}',
     "design_values": '{"R1": 36, "R2": 44, "R3": 10, "R4": 40, "R5": 10, "R6": 30, "R7": 24}',
     "node_voltages": '{"T": 47.60215, "n1": 26.17407, "n2": 20.87594, "n3": 20.49506}',
     "branch_currents": '{"R1": 0.5917947, "R2": 0.5917947, "R3": 4.775886, "R4": 0.671223, "R5": 0.671223, "R6": 0.671223, "R7": 1.961096}'},
    {"expected": "partial_open",
     "component_values": '{"R1": 647.404741, "R2": 43.122966, "R3": 9.905218, "R4": 39.876, "R5": 10.034657, "R6": 30.379183, "R7": 24.371938, "I1": 8}',
     "design_values": '{"R1": 36, "R2": 44, "R3": 10, "R4": 40, "R5": 10, "R6": 30, "R7": 24}',
     "node_voltages": '{"T": 51.318, "n1": 3.204773, "n2": 25.83088, "n3": 19.41714}',
     "branch_currents": '{"R1": 0.07431707, "R2": 0.07431707, "R3": 5.180905, "R4": 0.6391593, "R5": 0.6391593, "R6": 0.6391593, "R7": 2.105618}'},
    {"expected": "wrong_component_type",
     "component_values": '{"R1": 35.362887, "R2": 43.816073, "R3": 10.083336, "R4": 40.681598, "R5": 1.79e-06, "R6": 29.411244, "R7": 23.889575, "I1": 8}',
     "design_values": '{"R1": 36, "R2": 44, "R3": 10, "R4": 40, "R5": 10, "R6": 30, "R7": 24}',
     "node_voltages": '{"T": 52.06218, "n1": 28.81018, "n2": 52.06218, "n3": 0.0}',
     "branch_currents": '{"R1": 0.6575254, "R2": 0.6575254, "R3": 5.16319, "R4": 0.0, "R6": 0.0, "R7": 2.179284}'},
    {"expected": "multi_fault",
     "component_values": '{"R1": 35.494573, "R2": 2.168176, "R3": 323.21149, "R4": 39.798465, "R5": 9.842447, "R6": 30.159291, "R7": 24.275854, "I1": 8}',
     "design_values": '{"R1": 36, "R2": 44, "R3": 10, "R4": 40, "R5": 10, "R6": 30, "R7": 24}',
     "node_voltages": '{"T": 95.95792, "n1": 5.524123, "n2": 48.10118, "n3": 36.26586}',
     "branch_currents": '{"R1": 2.54782, "R2": 2.54782, "R3": 0.296889, "R4": 1.202477, "R5": 1.202477, "R6": 1.202477, "R7": 3.952813}'},
]


def main():
    n_correct = 0
    print(f"{'#':4s} {'expected':22s} {'predicted':22s} {'ok?':4s} label confidences")
    print("-" * 100)
    for i, case in enumerate(TEST_CASES, start=1):
        overall_pred, label_probs = predict_one(case)
        ok = (overall_pred == case["expected"])
        n_correct += ok

        conf_str = ", ".join(f"{label}={p:.0%}" for label, p in label_probs.items())
        print(f"{i:<4d} {case['expected']:22s} {overall_pred:22s} "
              f"{'OK' if ok else 'FAIL':4s} {conf_str}")

    print("-" * 100)
    print(f"Accuracy on this battery: {n_correct}/{len(TEST_CASES)} "
          f"({n_correct/len(TEST_CASES):.1%})")
    print(f"(threshold used to decide a label 'fired': {THRESHOLD:.0%})")


if __name__ == "__main__":
    main()